services:
  server:
    build:
      context: .
      target: PROD
    ports:
      - 25565:25565
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.2-alpine
    container_name: bwc-redis
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning
  db:
    image: mariadb:latest
    container_name: home-db
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: userpw
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: enx_plugin
    ports:
      - 3306:3306